#!/usr/bin/env python3
"""Embed a VGM (or gzip-compressed VGZ) file as a C header for the pico2 player.

Emits TUNE_VGM_DATA / TUNE_VGM_LEN / TUNE_VGM_NAME / TUNE_VGM_ARTIST. Track
name and author come from the GD3 tag (English fields) when present, with
fallbacks. Each header gets a distinct include guard so several can coexist
on disk and be selected by tune_vgm.h at compile time.

Usage:
    vgm_to_header.py INPUT.vgm OUTPUT.h --guard TUNE_FOO_H
    vgm_to_header.py "INPUT.vgz" OUTPUT.h --guard TUNE_FOO_H --name "Foo" --artist "Bar"
"""
import argparse
import gzip
import struct
import sys


def read_vgm(path):
    data = open(path, "rb").read()
    if data[:2] == b"\x1f\x8b":  # gzip magic -> .vgz
        data = gzip.decompress(data)
    if data[:4] != b"Vgm ":
        sys.exit(f"{path}: not a VGM file (bad magic {data[:4]!r})")
    return data


def parse_gd3(data):
    """Return (track_en, author_en) from the GD3 tag, or (None, None)."""
    gd3_rel = struct.unpack("<I", data[0x14:0x18])[0]
    if not gd3_rel:
        return None, None
    g = 0x14 + gd3_rel
    if data[g:g + 4] != b"Gd3 ":
        return None, None
    payload_len = struct.unpack("<I", data[g + 8:g + 12])[0]
    raw = data[g + 12:g + 12 + payload_len]
    fields = raw.decode("utf-16-le", errors="replace").split("\x00")
    # GD3 field order: 0 TrackEN, 1 TrackJP, 2 GameEN, 3 GameJP,
    # 4 SystemEN, 5 SystemJP, 6 AuthorEN, 7 AuthorJP, ...
    track = fields[0].strip() if len(fields) > 0 and fields[0].strip() else None
    author = fields[6].strip() if len(fields) > 6 and fields[6].strip() else None
    return track, author


def c_escape(s):
    out = []
    for ch in s:
        c = ord(ch)
        if 32 <= c < 127 and ch not in ('"', "\\"):
            out.append(ch)
        else:
            out.append("\\x%02x" % c)
    return "".join(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("input")
    ap.add_argument("output")
    ap.add_argument("--guard", required=True)
    ap.add_argument("--name", help="override track name (else from GD3)")
    ap.add_argument("--artist", help="override artist (else from GD3)")
    args = ap.parse_args()

    data = read_vgm(args.input)
    gd3_name, gd3_artist = parse_gd3(data)
    name = args.name or gd3_name or "Unknown"
    artist = args.artist or gd3_artist or "Unknown"

    lines = [
        "/* Auto-generated by scripts/vgm_to_header.py. Do not edit. */",
        f"/* Source: {c_escape(artist)} - {c_escape(name)} ({len(data)} bytes) */",
        f"#ifndef {args.guard}",
        f"#define {args.guard}",
        "#include <stdint.h>",
        "#include <stddef.h>",
        f'static const char TUNE_VGM_NAME[] = "{c_escape(name)}";',
        f'static const char TUNE_VGM_ARTIST[] = "{c_escape(artist)}";',
        "static const uint8_t TUNE_VGM_DATA[] = {",
    ]
    per_line = 16
    for i in range(0, len(data), per_line):
        chunk = data[i:i + per_line]
        lines.append("    " + ", ".join("0x%02x" % b for b in chunk) + ",")
    lines.append("};")
    lines.append("static const size_t TUNE_VGM_LEN = sizeof(TUNE_VGM_DATA);")
    lines.append(f"#endif /* {args.guard} */")

    open(args.output, "w").write("\n".join(lines) + "\n")
    print(f"wrote {args.output}: {name} / {artist} ({len(data)} bytes)")


if __name__ == "__main__":
    main()
